CREATE PROCEDURE sp_EnrollStudentTransaction
@StudentID INT,
@CourseID INT
AS
BEGIN
BEGIN TRANSACTION
BEGIN TRY

INSERT INTO Enrollments(StudentID,CourseID,EnrollmentDate)
VALUES(@StudentID,@CourseID,GETDATE())

COMMIT TRANSACTION

END TRY
BEGIN CATCH

ROLLBACK TRANSACTION
PRINT ERROR_MESSAGE()

END CATCH
END;